#!/usr/bin/env python3
"""List ngpestelos-mirrors dests whose description is a mirror, write mirrors.yml.

Default branch comes from UPSTREAM, not dest. Skips forks and excludes.yml.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAT = re.compile(
    r"^(?:Public full-history mirror of |Mirror of )"
    r"([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)",
    re.I,
)
BIG_120 = {
    "rails",
    "spree",
    "ansible",
    "atom",
}


def gh_json(args: list[str]):
    p = subprocess.run(["gh", *args], capture_output=True, text=True)
    if p.returncode != 0:
        raise RuntimeError(p.stderr[:400])
    return json.loads(p.stdout)


def gh_text(args: list[str]) -> tuple[int, str, str]:
    p = subprocess.run(["gh", *args], capture_output=True, text=True)
    return p.returncode, p.stdout.strip().strip('"'), p.stderr


def timeout_for(dest: str, src: str) -> int:
    if dest == "kubernetes" or src.endswith("/kubernetes"):
        return 360
    if dest in BIG_120 or src in {
        "rails/rails",
        "spree/spree",
        "ansible/ansible",
        "atom/atom",
    }:
        return 120
    return 60


def load_excludes() -> set[str]:
    path = ROOT / "excludes.yml"
    if not path.exists():
        return set()
    out = set()
    for line in path.read_text().splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if s.startswith("- "):
            out.add(s[2:].split("#", 1)[0].strip())
    return out


def main() -> int:
    repos = gh_json(
        [
            "repo",
            "list",
            "ngpestelos-mirrors",
            "--limit",
            "1000",
            "--json",
            "name,description,isPrivate,isFork,defaultBranchRef",
        ]
    )
    excludes = load_excludes()
    cands = []
    for r in repos:
        desc = r.get("description") or ""
        m = PAT.search(desc)
        if not m:
            continue
        if r.get("isFork"):
            print("skip fork", r["name"], file=sys.stderr)
            continue
        dest = r["name"]
        if dest in excludes:
            print("skip exclude", dest, file=sys.stderr)
            continue
        cands.append(
            {
                "dest": dest,
                "src": m.group(1),
                "dest_default": (r.get("defaultBranchRef") or {}).get("name"),
                "private": bool(r.get("isPrivate")),
            }
        )

    def up_default(src: str) -> tuple[str, str | None]:
        rc, out, _err = gh_text(["api", f"repos/{src}", "--jq", ".default_branch"])
        if rc != 0 or not out or out == "null":
            return src, None
        return src, out

    up: dict[str, str | None] = {}
    with ThreadPoolExecutor(max_workers=6) as ex:
        futs = [ex.submit(up_default, c["src"]) for c in cands]
        for fut in as_completed(futs):
            src, br = fut.result()
            up[src] = br

    rows = []
    for c in sorted(cands, key=lambda x: x["dest"].lower()):
        br = up.get(c["src"])
        if not br:
            print("skip no-upstream-default", c["dest"], c["src"], file=sys.stderr)
            continue
        rows.append(
            {
                "dest": c["dest"],
                "src": c["src"],
                "default": br,
                "timeout": timeout_for(c["dest"], c["src"]),
                "private": c["private"],
            }
        )

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    lines = [
        "# Generated by scripts/harvest.py. Default branch is UPSTREAM.",
        f"# dests={len(rows)} generated={stamp}",
        "mirrors:",
    ]
    for r in rows:
        priv = "true" if r["private"] else "false"
        lines.append(f"  - dest: {r['dest']}")
        lines.append(f"    src: {r['src']}")
        lines.append(f"    default: {r['default']}")
        lines.append(f"    timeout: {r['timeout']}")
        lines.append(f"    private: {priv}")
    (ROOT / "mirrors.yml").write_text("\n".join(lines) + "\n")
    print(f"wrote {len(rows)} dests to mirrors.yml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
